// Generated by CoffeeScript 1.10.0
(function() {
  var bin;

  bin = (function() {
    var hex, rect, tri;

    function bin() {}

    rect = function() {};

    tri = function() {};

    hex = function() {};

    quantile(function() {});

    boundry(function() {});

    voronoi(function() {});

    dot(function() {});

    stem(function() {});

    return bin;

  })();

}).call(this);

//# sourceMappingURL=bin.js.map
