// Generated by CoffeeScript 1.10.0
(function() {
  var link;

  link = (function() {
    var complete, delaunay, hill, join, mst, neighbor, sequence, tsp;

    function link() {}

    join = function() {};

    sequence = function() {};

    mst = function() {};

    delaunay = function() {};

    hill = function() {};

    tsp = function() {};

    complete = function() {};

    neighbor = function() {};

    return link;

  })();

}).call(this);

//# sourceMappingURL=link.js.map
