// Generated by CoffeeScript 1.10.0
(function() {
  var region;

  region = (function() {
    var config, mean, reange, sd, se, smooth, spread;

    function region() {}

    spread = function() {};

    sd = function() {};

    se = function() {};

    reange = function() {};

    config = function() {};

    mean = function() {};

    smooth = function() {};

    return region;

  })();

}).call(this);

//# sourceMappingURL=region.js.map
