// Generated by CoffeeScript 1.10.0
(function() {
  var summary;

  summary = (function() {
    var count, leaf, mean, median, mode, proportion, range, sd, se, sum;

    function summary() {}

    count = function() {};

    proportion = function() {};

    sum = function() {};

    mean = function() {};

    median = function() {};

    mode = function() {};

    sd = function() {};

    se = function() {};

    range = function() {};

    leaf = function() {};

    return summary;

  })();

}).call(this);

//# sourceMappingURL=summary.js.map
